Generate placeholder project

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -63,4 +63,40 @@ jobs:
           sf version
         shell: bash
 
-        
+      - name: Generate placeholder Salesforce project
+        id: generate_sf_project
+        if: steps.verify_target_file.outcome == 'success'
+        run: |
+          # This is needed as you may only execute project deployments from within a SF directory.
+          # This approach of using a placeholder project rather than the actual repository
+          # saves approximately 3 minutes of execution cost time thereby saving money.
+          sf project generate --name salesforce --template empty --output-dir $GITHUB_WORKSPACE
+          ls -laR $GITHUB_WORKSPACE  # temp debug
+        shell: bash
+
+      - name: Generate the deployment package manifest
+        id: generate_manifest_file
+        if: steps.generate_sf_project.outcome == 'success'
+        run: |
+          mkdir -p $GITHUB_WORKSPACE/salesforce/manifest
+          cat <<EOF > $GITHUB_WORKSPACE/salesforce/manifest/package.xml
+          <Package xmlns="http://soap.sforce.com/2006/04/metadata">
+            <types>
+              <members>MyStaticResource</members>
+              <name>StaticResource</name>
+            </types>
+            <version>59.0</version>
+          </Package>
+          EOF
+
+          if [ ! -f "$GITHUB_WORKSPACE/salesforce/manifest/package.xml" ]; then
+            echo "::error file=$GITHUB_WORKSPACE/salesforce/manifest/package.xml::Error: The manifest file does not exist."
+            exit 1
+          fi
+        shell: bash
+
+      - name: Echo the manifest file
+        if: steps.generate_manifest_file.outcome == 'success'
+        run: |
+          cat $GITHUB_WORKSPACE/salesforce/manifest/package.xml
+        shell: bash
